### ISSUE TITLE
Generated express app returns promise warnings

### ISSUE THREAD

**Issue by cjus** [flywheelsports/generator-fwsp-hydra#15]
```shell
┏━➤ [18:20:00]: ~/dev/flywheelsports/test-service
┗━➤ npm start

> test-service@0.0.1 start /Users/cjustiniano/dev/flywheelsports/test-service
> node test-service.js

(node:6925) Warning: a promise was created in a handler at /Users/cjustiniano/dev/flywheelsports/test-service/node_modules/fwsp-hydra-express/index.js:175:23 but was not returned from it, see http://goo.gl/rRqMUw
    at new Promise (/Users/cjustiniano/dev/flywheelsports/test-service/node_modules/bluebird/js/release/promise.js:77:14)
(node:6925) Warning: a promise was created in a handler at /Users/cjustiniano/dev/flywheelsports/test-service/node_modules/fwsp-hydra-express/index.js:177:24 but was not returned from it, see http://goo.gl/rRqMUw
    at new Promise (/Users/cjustiniano/dev/flywheelsports/test-service/node_modules/bluebird/js/release/promise.js:77:14)
(node:6925) Warning: a promise was created in a handler at /Users/cjustiniano/dev/flywheelsports/test-service/node_modules/fwsp-hydra/index.js:95:24 but was not returned from it, see http://goo.gl/rRqMUw
    at new Promise (/Users/cjustiniano/dev/flywheelsports/test-service/node_modules/bluebird/js/release/promise.js:77:14)
INFO
{ event: 'info',
  message: 'Successfully reconnected to redis server' }
INFO
{ event: 'start',
  message: 'test-service (v.0.0.1) server listening on port 33142' }
INFO
{ event: 'info', message: 'Using environment: development' }
(node:6925) Warning: a promise was created in a handler at /Users/cjustiniano/dev/flywheelsports/test-service/node_modules/fwsp-hydra-express/index.js:288:19 but was not returned from it, see http://goo.gl/rRqMUw
    at Function.PromiseMapSeries [as mapSeries] (/Users/cjustiniano/dev/flywheelsports/test-service/node_modules/bluebird/js/release/each.js:11:12)
serviceInfo { serviceName: 'test-service',
  serviceIP: '10.1.1.171',
  servicePort: 33142 }
```

**Comment by cjus** [comment]
Looks like this may have been caused by an updated fwsp-hydra-express.  Perhaps after the plugin support additions.

**Comment by cjus** [comment]
Confirmed that rolling back to `"fwsp-hydra-express": "0.11.5"` has no promise warnings on start.

**Comment by emadum** [comment]
I've never been able to reproduce this. Are you still seeing it as an issue?
