### ISSUE TITLE
Starting the generator in a folder that was generated seems to be an issue

### ISSUE THREAD

**Issue by cjus** [flywheelsports/generator-fwsp-hydra#4]
```shell
┏━➤ [10:03:10]: ~/dev/hello-service
┗━➤ yo fwsp-hydra
/Users/cjustiniano/.nvm/versions/node/v6.9.2/lib/node_modules/generator-fwsp-hydra/app/node_modules/mem-fs-editor/lib/actions/read-json.js:8
      throw new Error('Could not parse JSON in file: ' + filepath + '. Detail: ' + error.message);
      ^

Error: Could not parse JSON in file: /Users/cjustiniano/dev/hello-service/package.json. Detail: Unexpected token . in JSON at position 338
    at EditionInterface.module.exports [as readJSON] (/Users/cjustiniano/.nvm/versions/node/v6.9.2/lib/node_modules/generator-fwsp-hydra/app/node_modules/mem-fs-editor/lib/actions/read-json.js:8:13)
    at child.Base.determineAppname (/Users/cjustiniano/.nvm/versions/node/v6.9.2/lib/node_modules/generator-fwsp-hydra/app/node_modules/yeoman-generator/lib/base.js:773:23)
    at child.Base (/Users/cjustiniano/.nvm/versions/node/v6.9.2/lib/node_modules/generator-fwsp-hydra/app/node_modules/yeoman-generator/lib/base.js:156:23)
    at new child (/Users/cjustiniano/.nvm/versions/node/v6.9.2/lib/node_modules/generator-fwsp-hydra/app/node_modules/class-extend/index.js:25:41)
    at Environment.instantiate (/Users/cjustiniano/.nvm/versions/node/v6.9.2/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:336:10)
    at Environment.create (/Users/cjustiniano/.nvm/versions/node/v6.9.2/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:313:15)
    at Environment.run (/Users/cjustiniano/.nvm/versions/node/v6.9.2/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:372:24)
    at /Users/cjustiniano/.nvm/versions/node/v6.9.2/lib/node_modules/yo/lib/cli.js:140:11
    at Array.forEach (native)
    at /Users/cjustiniano/.nvm/versions/node/v6.9.2/lib/node_modules/yo/lib/cli.js:139:9
    at Environment.resolver.lookup (/Users/cjustiniano/.nvm/versions/node/v6.9.2/lib/node_modules/yo/node_modules/yeoman-environment/lib/resolver.js:50:12)
    at init (/Users/cjustiniano/.nvm/versions/node/v6.9.2/lib/node_modules/yo/lib/cli.js:115:7)
    at pre (/Users/cjustiniano/.nvm/versions/node/v6.9.2/lib/node_modules/yo/lib/cli.js:73:3)
    at Object.<anonymous> (/Users/cjustiniano/.nvm/versions/node/v6.9.2/lib/node_modules/yo/lib/cli.js:194:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
```

**Comment by emadum** [comment]
I'm unable to reproduce this one - that error looks like it was probably from #2.
